name:  TF-Drift Calling workflow from Clouddrove
on:
    workflow_dispatch:


jobs:
  calling_workflow_tfdrift-clouddrove:
    uses: 
        clouddrove/github-shared-workflows/.github/workflows/tfdrift.yml@master
    with:
        working_directory: "."
        provider: "aws"
        terraform_version: "1.3.6"
    secrets:
        aws_access_key_id: ${{ secrets.aws_access_key_id }}
        aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
        GITHUB: ${{ secrets.GITHUB }}
        
