name:  TF-Drift Calling workflow Using Smurf
on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read


jobs:
  calling_Smurf_workflow_tfdrift-clouddrove:
    uses: imran-cd/multiple-ec2/.github/workflows/shared-smurf-drift.yml@main
    with:
        smurf_version: "latest"
        aws_region: "us-east-2"
        working_directory: "."
        terraform_version: "1.8.5"
    secrets:
        aws_access_key_id: ${{ secrets.aws_access_key_id }}
        aws_secret_access_key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
        
