name: "Terraform Check drift Using Smurf"

on:
  workflow_call:
    inputs:
      smurf_version:
        required: false
        default: "latest"
        type: string

      terraform_version:
        required: false
        default: "1.8.5"
        type: string

      working_directory:
        required: false
        type: string
        default: "."

      aws_region:
        required: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  drift_check:
    name: Terraform drift check (SMURF)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      id-token: write
      contents: read
      issues: write

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: ðŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: Install Smurf
        uses: clouddrove/smurf@master
        with:
          version: ${{ inputs.smurf_version }}

      - name: âš™ï¸ Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: false

      - name: â˜ï¸ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: ðŸš€ Terraform init (Smurf)
        run: smurf stf init

      - name: ðŸŽ¨ Terraform fmt (Smurf)
        run: smurf stf fmt --timeout 10s

     
      - name: ðŸ“¡ Terraform Drift (Smurf)
        id: smurf-drift
        shell: bash
        run: |
          smurf stf drift | sed -r "s/\x1B\[[0-9;]*[mK]//g" | tee drift.txt

      
      - name: Detect drift from SMURF output
        id: drift-detect
        shell: bash
        run: |
          if grep -Eq "\[(update|create|delete|replace)\]" drift.txt; then
            echo "drift=true" >> $GITHUB_OUTPUT
          else
            echo "drift=false" >> $GITHUB_OUTPUT
          fi

      
      - name: ðŸ’¾ Upload Drift Report Artifact
        if: ${{ steps.drift-detect.outputs.drift == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: smurf-drift-report
          path: drift.txt

      
      - name: ðŸ§µ Create String Output
        id: drift-string
        shell: bash
        run: |
          DRIFT_OUTPUT="$(cat drift.txt)"
          delimiter="$(openssl rand -hex 8)"

          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "### Working Directory: \`${{ inputs.working_directory }}\`" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          echo "$DRIFT_OUTPUT" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      
      - name: ðŸ“ Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.drift-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      
      - name: ðŸš¨ Publish Drift Report and create/update issue
        if: steps.drift-detect.outputs.drift == 'true'
        uses: actions/github-script@v8
        env:
          SUMMARY: "${{ steps.drift-string.outputs.summary }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `${process.env.SUMMARY}`;
            const title = 'Terraform Configuration Drift Detected (SMURF)';
            const creator = 'github-actions[bot]'

            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })

            const driftIssues = issues.data.filter(
              (i) => i.title === title && i.user.login === creator
            )

            if (driftIssues.length > 0) {
              const issue = driftIssues[0]
              console.log('Drift Detected: Updating existing issue')

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: body
              })
            } else {
              console.log('Drift Detected: Creating new issue')

              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['terraform', 'drift']
              })
            }

     
      - name: âœ… Publish Drift Report (close issue if resolved)
        if: steps.drift-detect.outputs.drift == 'false'
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = 'Terraform Configuration Drift Detected (SMURF)';
            const creator = 'github-actions[bot]'

            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })

            const driftIssues = issues.data.filter(
              (i) => i.title === title && i.user.login === creator
            )

            if (driftIssues.length > 0) {
              const issue = driftIssues[0]

              console.log('No Drift: Closing drift issue')

              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              })
            }
